AGENT_BINARY_NAME = "f5-lbaasv2-bigiq-agent"

LBAASV2_BIGIQ_AGENT_TYPE = "F5 LBaasV2 BIG-IQ Agent"

TOPIC_LBAASV2_BIGIQ_DRIVER = "f5-lbaasv2-bigiq-driver"

TOPIC_LBAASV2_BIGIQ_AGENT = "f5-lbaasv2-bigiq-agent"

RPC_API_VERSION = "1.0"

# Provisioning Status
ACTIVE = "ACTIVE"
PENDING_CREATE = "PENDING_CREATE"
PENDING_UPDATE = "PENDING_UPDATE"
PENDING_DELETE = "PENDING_DELETE"
ERROR = "ERROR"

# Operating Status
OFFLINE = "OFFLINE"
ONLINE = "ONLINE"
